version: "3.8"

services:
  # Servicio de la aplicación Go/Fiber
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/nihongo"
      REDIS_ADDR: "redis:6379"
      JWT_SECRET: "your-jwt-secret"
      REVENUECAT_API_KEY: "your-revenuecat-api-key"
      REVENUECAT_BASE_URL: "https://api.revenuecat.com/v1"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  # Servicio de la base de datos MongoDB
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # Servicio de la caché Redis
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:
